//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookInfo
    {
        public int bookID { get; set; }
        public string bookName { get; set; }
        public decimal bookPrice { get; set; }
        public string bookImg { get; set; }
        public Nullable<int> onlyBuy { get; set; }
        public string isDel { get; set; }
        public string bookNotes { get; set; }
    }
}
