//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsInfo
    {
        public int newsId { get; set; }
        public string newsTitle { get; set; }
        public string newsContent { get; set; }
        public System.DateTime sumitTime { get; set; }
        public string submitor { get; set; }
        public string submitId { get; set; }
    }
}
