//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderInfo
    {
        public long orderId { get; set; }
        public string submitTime { get; set; }
        public string buyUser { get; set; }
        public string toName { get; set; }
        public string toAddress { get; set; }
        public string toPhone { get; set; }
        public string orderState { get; set; }
        public string payType { get; set; }
    }
}
