//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toInfo
    {
        public int sysid { get; set; }
        public string toTitle { get; set; }
        public string toName { get; set; }
        public string toAddress { get; set; }
        public string toPhone { get; set; }
        public string userName { get; set; }
    }
}
